import fs from 'fs';
let content = fs.readFileSync('src/App.tsx', 'utf8');
content = content.replace(/bg-\[\#f5f5f0\]/g, 'bg-[var(--bg-primary)]');
content = content.replace(/bg-white/g, 'bg-[var(--bg-secondary)]');
content = content.replace(/text-\[\#333\]/g, 'text-[var(--text-primary)]');
content = content.replace(/text-\[\#4a4a4a\]/g, 'text-[var(--text-primary)]');
content = content.replace(/text-\[\#5A5A40\]/g, 'text-[var(--accent)]');
content = content.replace(/bg-\[\#5A5A40\]/g, 'bg-[var(--accent)]');
content = content.replace(/text-\[\#8c8c73\]/g, 'text-[var(--text-secondary)]');
content = content.replace(/text-\[\#b3b3a6\]/g, 'text-[var(--text-muted)]');
content = content.replace(/border-\[\#e5e5df\]/g, 'border-[var(--border)]');
content = content.replace(/border-\[\#f0f0eb\]/g, 'border-[var(--border-light)]');
content = content.replace(/bg-\[\#f9f9f6\]/g, 'bg-[var(--bg-tertiary)]');
content = content.replace(/hover:text-\[\#5A5A40\]/g, 'hover:text-[var(--accent)]');
content = content.replace(/hover:bg-\[\#f5f5f0\]/g, 'hover:bg-[var(--bg-primary)]');
content = content.replace(/hover:bg-\[\#4a4a35\]/g, 'hover:bg-[var(--accent-hover)]');
content = content.replace(/focus:ring-\[\#5A5A40\]/g, 'focus:ring-[var(--accent)]');
content = content.replace(/focus:border-\[\#5A5A40\]/g, 'focus:border-[var(--accent)]');
content = content.replace(/ring-\[\#5A5A40\]/g, 'ring-[var(--accent)]');
content = content.replace(/stroke="#5A5A40"/g, 'stroke="var(--accent)"');
content = content.replace(/fill: '#5A5A40'/g, "fill: 'var(--accent)'");
content = content.replace(/fill="#8c8c73"/g, 'fill="var(--text-secondary)"');
content = content.replace(/fill: '#8c8c73'/g, "fill: 'var(--text-secondary)'");
content = content.replace(/fill: '#4a4a4a'/g, "fill: 'var(--text-primary)'");
content = content.replace(/stroke="#f0f0eb"/g, 'stroke="var(--border-light)"');
fs.writeFileSync('src/App.tsx', content);
